name: Tests
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    - run: pip install -r requirements-dev.txt
#    - run: flake8 src
    - name: Install package
        run: |
          pip install .
    - name: Run test
        run: |
          pytest -ra
