name: Tests
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    - name: Set up package requirements
      run: pip install -r requirements.txt
    - name: Set up dev requirements
      run: pip install -r requirements-dev.txt
#    - run: flake8 src
    - name: Install package
      run: |
          pip install .
    - name: Run test
      run: |
          pytest -ra
